# ZSH_THEME="agnoster" # set by `omz`
export DEFAULT_USER="reillyfreret"
export ZSH="$HOME/.oh-my-zsh"
COMPLETION_WAITING_DOTS="true"
typeset -U fpath
fpath=("$HOME/.zfunc" $fpath)
plugins=(git python chezmoi)
source $ZSH/oh-my-zsh.sh

alias tree="tree -L 2 -a"

alias pi='kitty +kitten ssh freret@192.168.8.235'
alias pir='kitty +kitten ssh freret@100.109.17.69'
alias router='ssh root@192.168.8.1'
alias c='cursor'
alias z='zed'
alias gfp='git fetch -p'
alias gitrb='git removed-branches'
alias gitrbpf='git removed-branches --prune --force'
alias gcm='git commit --verbose -m'
alias gs='git status'
alias ghprcw='gh pr checks --watch'
alias ghmerge='gh pr merge -sd'
alias ghview='gh pr view --web'
alias ghcomment='gh pr comment -b'
alias ncduc='ncdu --color dark'
alias cz='chezmoi'
alias nv='nvim'

bindkey '^u' backward-kill-line
bindkey '^k' kill-line

function rfind {
  if [[ -z "$1" ]]; then
    echo "no arguments passed; aborting"
    return
  fi
  mdfind "kMDItemFSName=='*$1*'cd"
}

# list most recent files in pwd
function lr() {
  local n="${1:-5}"
  ls -lt | grep -v '^total' | head -n "$n"
}

utcnow() {
  date -u +"%Y-%m-%dT%H:%M:%S"
}

# nanobrew
export PATH="/opt/nanobrew/prefix/bin:$PATH"

# mise
eval "$(mise activate zsh)"

# chezmoi
export PATH="$HOME/bin:$PATH"

# starship
eval "$(starship init zsh)"

export PATH="$HOME/.local/bin:$PATH"
